### ISSUE TITLE
Does not give me any info

### ISSUE THREAD

**Issue by jerhone** [networklore/ansible-snmp-facts#2] opened 2016-01-04 10:15 UTC
Hi,

Am using Ansible 1.9.1 and I have tried to run a simple playbook as illustrated in sample playbooks e.g.

---
- hosts: firewall
  connection: local
  gather_facts: false
  tasks:
  - name: Get SNMP details from firewall
    snmp_facts: host={{ inventory_hostname }} version=v2c community=public

But it does not give me any info even with the -v option like below...

[root@jerhone ansible]# ansible-playbook snmp_facts.yml -v

PLAY [firewall] ***************************************************************

TASK: [Get SNMP details from firewall] ****************************************
ok: [192.168.1.1] => {"ansible_facts": {"ansible_all_ipv4_addresses": []}, "changed": false}

PLAY RECAP ********************************************************************
192.168.1.1                : ok=1    changed=0    unreachable=0    failed=0

I am still learning Ansible since I find it very useful for me. 
I am not sure what I am missing since this module is already included in 1.9 versions right?

Appreciate if you can assist me on this.

**Comment by ogenstad** [comment] 2016-01-04 10:47
Hi,

Since this module got included in Ansible 1.9 I don't update it here any longer (though perhaps I should). The problem is that this module relies on pysnmp which changed its behaviour after 4.3.0. I've submitted a patch to Ansible, but I'm not sure if it's been included in any of the releases yet. It will be included in Ansible 2.0 which _should_ be out January 6th. However you can also download the module from https://github.com/ansible/ansible-modules-extras/blob/devel/network/snmp_facts.py

Another option would be to install an earlier version of pysnmp:
pip uninstall pysnmp
pip install pysnmp==4.2.5

Let me know how it works out and I'll close this issue.

Regards
Patrick

**Comment by jerhone** [comment] 2016-01-04 16:00
Hi Patrick,

It worked. However, I also need to uninstall pycrypto. Appreciate your help! I will upgrade to Ansible 2.0 soon. You are a life saver!

**Comment by GivingYu** [comment] 2017-04-05 10:11
ansible 2.2.2.0
pysnmp 4.2.5

[root@pydev ansible-snmp-facts]# ansible-playbook -i inventory snmp_facts-playbook.yml -v  
Using /etc/ansible/ansible.cfg as config file

PLAY [switches] ****************************************************************

TASK [Get SNMP information from switches] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: setComponentByType() got multiple values for keyword argument 'verifyConstraints'
fatal: [10.1.1.2]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_jmWAZs/ansible_module_snmp_facts.py\", line 364, in <module>\n    main()\n  File \"/tmp/ansible_jmWAZs/ansible_module_snmp_facts.py\", line 250, in main\n    cmdgen.MibVariable(p.sysLocation,),\n  File \"/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py\", line 424, in getCmd\n    kwargs.get('contextName', null)\n  File \"/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py\", line 280, in getCmd\n    contextEngineId, contextName\n  File \"/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pysnmp/entity/rfc3413/cmdgen.py\", line 300, in sendReq\n    v2c.apiPDU.setVarBinds(reqPDU, varBinds)\n  File \"/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pysnmp/proto/api/v1.py\", line 103, in setVarBinds\n    varBindList.getComponentByPosition(idx), varBind\n  File \"/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pysnmp/proto/api/v1.py\", line 33, in setOIDVal\n    varBind.setComponentByPosition(1).getComponentByPosition(1).setComponentByType(val.getTagSet(), val, 1, verifyConstraints=False)\nTypeError: setComponentByType() got multiple values for keyword argument 'verifyConstraints'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/root/ansible-snmp-facts/snmp_facts-playbook.retry

PLAY RECAP *********************************************************************
10.1.1.2                   : ok=0    changed=0    unreachable=0    failed=1

**Comment by ogenstad** [comment] 2017-07-10 05:51
Since Ansible 1.9 this module has shipped as part of Ansible. If there's still a problem, please open an [issue here](https://github.com/ansible/ansible/issues) instead.

**Closed as completed by ogenstad** 2017-07-10 05:51 UTC
